# Site settings
title: Tiago Januario
description: Assistant Professor
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tiago Januario
user_description: Assistant Professor, Department of Computer Science of Institute of Mathematics and Statistics of Universidade Federal da Bahia, at Salvador, state of Bahia, Brazil.
user_title: Assistant Professor
email: januario@ufba.br
# twitter_username: lorem_ipsum
github_username:  januarioccp
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-62734213-1"

exclude: ['package.json', 'src' , 'node_modules']
